version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "!TesteDockerRedis1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - redis
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=DemoDockerAndRedisDb;User Id=sa;Password=!TesteDockerRedis1;Encrypt=false;TrustServerCertificate=true;
      - Redis__Connection=redis:6379
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge